-- Synapse Dedicated does not support the time-zone conversion generated by
-- dbt_date.get_base_dates. Generate a fixed daily spine with native T-SQL.
with digits as (

    select 0 as n union all select 1 union all select 2 union all select 3 union all select 4
    union all select 5 union all select 6 union all select 7 union all select 8 union all select 9

),

numbers as (

    select
        d0.n + 10 * d1.n + 100 * d2.n + 1000 * d3.n + 10000 * d4.n as n
    from digits as d0
    cross join digits as d1
    cross join digits as d2
    cross join digits as d3
    cross join digits as d4

)

select cast(dateadd(day, n, cast('2000-01-01' as date)) as date) as date_day
from numbers
where n < datediff(day, cast('2000-01-01' as date), cast('2030-01-01' as date))
